version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: erp
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB__CONNECTION: Host=postgres;Port=5432;Database=erp;Username=erp;Password=erp
      JWT__ISSUER: erp-local
      JWT__AUDIENCE: erp-web
      JWT__KEY: dev_dev_dev_dev_dev_dev_dev_dev_1234567890
    depends_on:
      - postgres
    ports:
      - "5000:8080"
  web:
    build: ./web
    environment:
      VITE_API_BASE: http://localhost:5000/api
    depends_on:
      - api
    ports:
      - "5173:5173"
volumes:
  db_data:
